---

- name: Install packages
  apt:
    pkg: munin-node
    state: installed

- name: Configure munin-node
  template:
    src: etc_munin_munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
  notify: restart munin-node

- name: Activate plugins
  include: plugins.yml
