---

- name: Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - postfix
    - libsasl2-2
    - sasl2-bin
    - libsasl2-modules
    - dovecot-common
    - dovecot-imapd
    - dovecot-sieve
    - dovecot-managesieved
    - opendkim
    - opendkim-tools
    - spamassassin
    - spamc

- name: Set mailname
  template:
    src: etc_mailname.j2
    dest: /etc/mailname

- include: tasks/dovecot.yml
- include: tasks/postfix.yml
- include: tasks/saslauth.yml
- include: tasks/opendkim.yml
- include: tasks/spamassassin.yml

- name: Create skel Maildir
  command: maildirmake.dovecot /etc/skel/{{ item }}
  args:
    creates: /etc/skel/{{ item }}
  with_items:
    - Maildir
    - Maildir/.Drafts
    - Maildir/.Junk
    - Maildir/.Sent
    - Maildir/.Trash
    - Maildir/.Templates

- name: Create mail users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: /bin/false
  with_items: "{{ mail_users }}"

- name: Create mail aliases
  lineinfile:
    dest: /etc/aliases
    regexp: "^{{ item.alias | regex_escape() }}\\s*:"
    line: "{{ item.alias }}: {{ item.user }}"
  with_items: "{{ mail_aliases }}"
  notify: update aliases

- name: Register domain
  include: roles/letsencrypt/tasks/domain.yml
  vars:
    domain: "{{ mail_domain }}"

- name: Add backup entry for mail users
  include: roles/backup/tasks/register_path.yml
  vars:
    name: maildir-{{ item.name }}
    path: /home/{{ item.name }}/Maildir
  with_items: "{{ mail_users }}"
