---

- name: Install package
  apt:
    pkg: munin
    state: installed

- name: Create config file
  template:
    src: etc_munin_munin.conf.j2
    dest: /etc/munin/munin.conf

- name: Register domain
  include: roles/letsencrypt/tasks/domain.yml
  vars:
    domain: "{{ munin_domain }}"

- name: Create nginx server config
  template:
    src: etc_nginx_sites-available_munin.j2
    dest: /etc/nginx/sites-available/munin
  notify: restart nginx

- name: Create nginx password file
  template:
    src: etc_nginx_passwd_munin.j2
    dest: /etc/nginx/passwd_munin
  notify: restart nginx

- name: Enable nginx server
  file:
    dest: /etc/nginx/sites-enabled/munin
    src: /etc/nginx/sites-available/munin
    state: link
  notify: restart nginx
