---

- name: Install fail2ban
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - fail2ban

- name: Setup fail2ban defaults
  ini_file:
    dest: /etc/fail2ban/jail.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: ignoreip, value: "127.0.0.1/8 192.168.0.1/16" }
    - { section: DEFAULT, option: bantime, value: 3600 }
    - { section: DEFAULT, option: findtime, value: 3600 }
    - { section: DEFAULT, option: maxretry, value: 3 }
  notify: restart fail2ban

- name: Setup fail2ban SSH jail
  ini_file:
    dest: /etc/fail2ban/jail.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: ssh, option: enabled, value: "true" }
    - { section: ssh, option: maxretry, value: 3 }
  notify: restart fail2ban

- name: Enable fail2ban recidive jail
  ini_file:
    dest: /etc/fail2ban/jail.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: recidive, option: enabled, value: "true" }
  notify: restart fail2ban
