---

- name: dnsmasq installation
  apt:
    pkg: dnsmasq
    state: present

- name: dnsmasq configuration
  template:
    src: etc_dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: reload dnsmasq
